// src/components/Footer.tsx
import React from 'react'
import { styled } from '../ui'

import { Content, Box, Img } from './Box'
import { Link, UnderlinedHeading, ExtraHeading } from './Text'
import { Socials } from './Socials'

import logo from '../assets/ambition_round_gradient_clean.svg'

export const StyledFooter = styled('footer', {
  background: '$mirage',
})

export const Footer: React.FC = () => {
  return (
    <StyledFooter>
      <Content>
        <Box
          align="centerX"
          justify="spaceBetweenX"
          css={{
            display: 'flex',
            '@initial': { flexDirection: 'column' },
            '@sm': { flexDirection: 'row' },
          }}
        >
          <Box
            direction="v"
            css={{
              // display: 'flex',
              '@initial': { justifyContent: 'center' },
              '@sm': {},
            }}
          >
            <UnderlinedHeading id="where-the-fuck">
              Where the fuck<ExtraHeading> (Socials)</ExtraHeading>
            </UnderlinedHeading>
            <Socials />
          </Box>
          <Box>
            <Link href="http://ambition.wtf" target="_blank">
              <Img
                src={logo}
                alt="Ambition logo"
                css={{ py: '$12', height: '$48' }}
              />
            </Link>
          </Box>
        </Box>
      </Content>
    </StyledFooter>
  )
}

// src/routes/_footer.svelte
<script lang="ts">
	import { stitch } from '@/ui'

	import Image from '$lib/atoms/Image.svelte'
	import Content from '$lib/bonds/Content.svelte'
	import Inline from '$lib/bonds/Inline.svelte'
	import Stack from '$lib/bonds/Stack.svelte'
	import HeadingExtra from '$lib/comps/HeadingExtra.svelte'
	import Socials from '$lib/comps/Socials.svelte'
	import HeadingUnderline from '$lib/comps/HeadingUnderline.svelte'

	import logo from '../assets/ambition_round_gradient_clean.svg'

	const ss = stitch({
		bg: '$mirage',
	})
</script>

<footer class={ss()}>
	<Content>
		<Inline
			collapseBelow="md"
			align="center"
			spaceV="sm"
			css={{
				justifyContent: 'space-between',
				'@initial': {
					py: '$0',
				},
				'@sm': {
					py: '$2',
				},
				'@md': {
					py: '$4',
				},
			}}>
			<Stack align="center" space="md">
				<HeadingUnderline id="where">
					Where The Fuck <HeadingExtra content="(Socials)" />
				</HeadingUnderline>
				<Socials size="xl" space="no" />
			</Stack>
			<Image
				url={logo}
				alt="Ambition logo"
				css={{
					my: '$16',
					height: '$48',
				}} />
		</Inline>
	</Content>
</footer>
